import { tool } from '@langchain/core/tools';
import { z } from 'zod';

import { renderVideoWithFfmpeg, videoEditPlanSchema } from '../creator-pipeline';

export const renderVideoWithFfmpegTool = tool(
  async ({ bucket, sourceKey, editPlan }) => {
    const output = await renderVideoWithFfmpeg({
      bucket,
      sourceKey,
      plan: videoEditPlanSchema.parse(editPlan),
    });

    return {
      status: 'rendered',
      output,
    };
  },
  {
    name: 'render_video_ffmpeg',
    description:
      'Execute an FFmpeg render using a structured edit plan generated by Amazon Nova.',
    schema: z.object({
      bucket: z.string().describe('The S3 bucket containing the staged source video.'),
      sourceKey: z.string().describe('The S3 key of the staged source video.'),
      editPlan: videoEditPlanSchema.describe('The structured edit plan to execute with FFmpeg.'),
    }),
  },
);
